[package]
name = "homr-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "unstable"]}
chrono = "0.4.19"
dotenv = "0.15.0"
log = "0.4.17"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.142", features = ["derive"]}
serde_json = "1.0.83"
sqlx = { version = "0.3.4", features = ["runtime-async-std", "macros", "chrono", "json", "postgres", "uuid"]}
thiserror = "1.0.32"
tide = "0.16.0"
uuid = "1.1.2"
